name: Video Notes Bot

on:
  push:
    paths:
      - 'video_link.txt'
  workflow_dispatch:

jobs:
  run-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          sudo apt-get install -y ffmpeg
          pip install -r requirements.txt

      - name: Run Lecture Script
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python cloud_lecture_bot.py
        
